##############################################################################
# Copyright (c) 2018 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

- name: fetch admin.conf
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: /opt/admin.conf
    flat: yes
  when: inventory_hostname == groups['kube_master'][0]
