##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Install yum epel-release
  command: yum -y install epel-release
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install yum packages
  yum:
    pkg: "{{ item }}"
    state: "present"
  with_items: "{{ packages }}"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    state: "present"
    update_cache: 'yes'
  with_items: "{{ packages }}"
  when: ansible_os_family == 'Debian'
