##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: install congress packages
  pip: name={{ item }} state=present
  with_items: "{{ pip_packages | union(packages_noarch) }}"

- name: create congress etc directory
  file: path=/etc/congress state=directory

- name: update congress conf
  template: src={{ item }} dest=/etc/congress/{{ item }}
            backup=yes
  with_items:
    - congress.conf
    - api-paste.ini
    - policy.json
  notify:
    - restart congress services

- name: create congress service
  copy: src=congress.service dest=/lib/systemd/system/

- name: create congress service work dir
  file: path=/var/lib/congress state=directory

- name: link the congress service
  file:
    src: /lib/systemd/system/congress.service
    dest: /etc/systemd/system/multi-user.target.wants/congress.service
    state: link
