---
packages:
  - ubuntu-cloud-keyring
  - python-dev
  - openvswitch-datapath-dkms
  - openvswitch-switch
  - python-memcache
  - python-iniparse
  #- python-d* #TODO, need remove

pip_packages:
  - crudini
  - python-keyczar

pip_conf: pip.conf

services:
  - ntp


