##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
packages:
  - openvswitch
  - python-devel
  - python-memcached
  - gcc
  - redhat-lsb-core
  - python-crypto
  - wget
  - yum-plugin-priorities
  - vim
  - lsof
  - strace
  - net-tools

pip_packages:
  - crudini
  - python-keyczar
  - shade
  - os-client-config

pip_conf: pip.conf

services:
  - openvswitch
  - ntpd
