##############################################################################
## Copyright (c) 2015 Nokia and others.
##
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Apache License, Version 2.0
## which accompanies this distribution, and is available at
## http://www.apache.org/licenses/LICENSE-2.0
###############################################################################
---

path: /tmp/kvmfornfv
kernel_path: "{{ pathÂ }}/kernel"
qemu_path: "{{ path }}/qemu"
qemu_build_dir: "{{ qemu_path }}/build"
package: kvmfornfv.tar.gz

