---
packages:
  - python-devel
  - python-pip
  - gcc
  - redhat-lsb-core
  - python-crypto
  - wget
  - yum-plugin-priorities
  - vim
  - lsof
  - strace
  - net-tools
  - git

pip_packages:
  - crudini
  - python-keyczar

pip_conf: pip.conf
