---
#- hosts: collector
#  sudo: yes
#  tasks:
 
- name: "temporary disable supervisor analytics"
  template:
#    src: "templates/override.j2"
    src: "../../templates/install/override.j2"
    dest: "/etc/init/supervisor-analytics.override"

- name: "install contrail openstack analytics package"
#   apt:
#   name: "contrail-openstack-analytics"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present force=yes"
  with_items: collector_package
