---
#- hosts: config
#  sudo: yes
#  tasks:
- name: "temporary disable supervisor config"
#  sudo: True
  template:
#        src: "templates/override.j2"
    src: "../../templates/install/override.j2"
    dest: "/etc/init/supervisor-config.override"

- name: "temporary disable neutron server"
#  sudo: True
  template:
#        src: "templates/override.j2"
    src: "../../templates/install/override.j2"
    dest: "/etc/init/neutron-server.override"

- name: "install contrail openstack config package"
#  sudo: True
#      apt:
#        name: "contrail-openstack-config"
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: config_packages
