---
- name: stop rabbitmq app
  command: rabbitmqctl stop_app; sleep 3

- name: join  cluster
  command: rabbitmqctl join_cluster rabbit@{{ haproxy_hosts.keys()[0] }}

- name: start rabbitmq app
  command: rabbitmqctl start_app
