---
#- hosts: config
#  sudo: yes
#  tasks:

- name: "recover rabbitmq-server service script"
  shell: if [ ! -f "\/etc\/init.d\/rabbitmq-server.initd.supervisord" ] ; then  mv /etc/init.d/rabbitmq-server.initd.supervisord /home/rabbitmq-server.initd.supervisord; mv /etc/init.d/rabbitmq-server /home/rabbit-server; mv /etc/init.d/rabbitmq-server.backup /etc/init.d/rabbitmq-server; fi

- name: "restart rabbitmq-server"
  service:
    name: "rabbitmq-server"
    state: "restarted"  

- name: "provision config node"
  shell: "python /opt/contrail/utils/provision_config_node.py --api_server_ip {{ contrail_haproxy_address }} --admin_user {{ contrail_admin_user }} --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --oper add --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }}"
  when: inventory_hostname in groups['opencontrail_config']

#- hosts: database
#  sudo: yes
#  tasks:
- name: "provision database node"
  shell: "python /opt/contrail/utils/provision_database_node.py --api_server_ip {{ contrail_haproxy_address }} --admin_user {{ contrail_admin_user }} --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --oper add --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }}"
  when: inventory_hostname in groups['opencontrail_database']
  
  
#- hosts: collector
#  sudo: yes
#  tasks:
- name: "provision collector node"
  shell: "python /opt/contrail/utils/provision_analytics_node.py --api_server_ip {{ contrail_haproxy_address }} --admin_user {{ contrail_admin_user }} --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --oper add --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }}"
  when: inventory_hostname in groups['opencontrail_collector']

#- hosts: control
#  sudo: yes
#  tasks:
- name: "provision control node"
  shell: "python /opt/contrail/utils/provision_control.py --api_server_ip {{ contrail_haproxy_address }} --api_server_port 8082 --admin_user {{ contrail_admin_user }} --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --oper add --host_name {{ ansible_hostname }} --host_ip {{ contrail_address }} --router_asn {{ contrail_router_asn }}"
  when: inventory_hostname in groups['opencontrail_control']
  
#- hosts: config
#  sudo: yes
#  tasks:
- name: "provision metadata services"
  shell: "python /opt/contrail/utils/provision_linklocal.py --api_server_ip {{ contrail_haproxy_address }} --admin_user {{ contrail_admin_user }} --admin_password {{ contrail_admin_password }} --admin_tenant_name admin --oper add --ipfabric_service_ip 10.84.50.1 --ipfabric_service_port 8775 --linklocal_service_name metadata --linklocal_service_ip 169.254.169.254 --linklocal_service_port 80"
  run_once: yes
  when: inventory_hostname in groups['opencontrail_config']


#- hosts: config
#  sudo: yes
#  tasks:
- name: "provision encap"
  shell: "python /opt/contrail/utils/provision_encap.py --api_server_ip {{ contrail_haproxy_address }} --admin_user {{ contrail_admin_user }} --admin_password {{ contrail_admin_password }} --oper add --encap_priority MPLSoUDP,MPLSoGRE,VXLAN"
  run_once: yes
  when: inventory_hostname in groups['opencontrail_config']
  
