##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---
nic_mappings: []
bond_mappings: []

provider_net_mappings:
  - name: br-provider
    network: physnet
    interface: eth1
    type: ovs
    role:
      - controller

sys_intf_mappings:
  - name: mgmt
    interface: eth0
    type: normal
    vlan_tag: None
    role:
      - controller
      - compute

  - name: tenant
    interface: eth2
    type: normal
    vlan_tag: None
    role:
      - controller

  - name: tenant
    interface: eth2
    type: dpdk
    vlan_tag: None
    role:
      - compute

  - name: storage
    interface: eth1
    type: normal
    vlan_tag: 102
    role:
      - controller
      - compute

  - name: external
    interface: eth1
    type: normal
    vlan_tag: None
    role:
      - controller
      - compute

ip_settings:
  - name: mgmt
    ip_ranges:
      - - "10.1.0.50"
        - "10.1.0.100"
    dhcp_ranges:
      - - "10.1.0.2"
        - "10.1.0.49"
    cidr: "10.1.0.0/24"
    gw: "10.1.0.1"
    role:
      - controller
      - compute

  - name: tenant
    ip_ranges:
      - - "172.16.1.1"
        - "172.16.1.50"
    cidr: "172.16.1.0/24"
    role:
      - controller
      - compute

  - name: storage
    ip_ranges:
      - - "172.16.2.1"
        - "172.16.2.50"
    cidr: "172.16.2.0/24"
    role:
      - controller
      - compute

  - name: external
    ip_ranges:
      - - "192.168.10.10"
        - "192.168.10.50"
    cidr: "192.168.10.0/24"
    gw: "192.168.10.1"
    role:
      - controller
      - compute

internal_vip:
  ip: 10.1.0.222
  netmask: "24"
  interface: mgmt

public_vip:
  ip: 192.168.10.222
  netmask: "24"
  interface: external

onos_nic: eth2
tenant_net_info:
  type: vxlan
  range: "1:1000"
  provider_network: None

public_net_info:
  enable: "True"
  network: ext-net
  type: flat
  segment_id: 1000
  subnet: ext-subnet
  provider_network: physnet
  router: router-ext
  enable_dhcp: "False"
  no_gateway: "False"
  external_gw: "192.168.10.1"
  floating_ip_cidr: "192.168.10.0/24"
  floating_ip_start: "192.168.10.100"
  floating_ip_end: "192.168.10.200"
