##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
mongodb_packages:
    - mongodb-server
    - mongodb-clients
    - python-pymongo

mysql_packages:
  - python-mysqldb
  - mysql-server

maridb_packages:
  - libaio1
  - libssl0.9.8
  - python-mysqldb
  - mysql-wsrep-server-5.5
  - galera-3

pip_packages: []

services: []

mongodb_service: mongodb
mysql_config:
  - dest: /etc/mysql/my.cnf
    src: my.cnf
  - dest: /etc/mysql/conf.d/wsrep.cnf
    src: wsrep.cnf

wsrep_provider_file: "/usr/lib/galera/libgalera_smm.so"
