##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: create all needed db
  mysql_db: login_unix_socket=/var/run/mysqld/mysqld.sock name={{ item.db }} state=present
  with_items: "{{ credentials }}"

- name: create service db user
  mysql_user:
    login_unix_socket=/var/run/mysqld/mysqld.sock
    name={{ item[0].user }}
    password={{ item[0].password }}
    priv=*.*:ALL,GRANT
    host={{ item[1] }}
    state=present
  with_nested:
    - "{{ credentials }}"
    - ['%', 'localhost', inventory_hostname]

- name: create wsrep db user
  mysql_user:
    login_unix_socket=/var/run/mysqld/mysqld.sock
    name={{ WSREP_SST_USER }}
    password={{ WSREP_SST_PASS }}
    priv=*.*:ALL,GRANT
    host={{ item }}
    state=present
  with_items: ['%', 'localhost', inventory_hostname]
