##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

- name: turn off neutron server and agent Daemon on control node
  shell: >
    sed -i '/{{ service_ovs_agent_name }}/d' /opt/service ;
    sed -i '/neutron-server/d' /opt/service;
    sed -i '/keepalived/d' /opt/service;

- name: turn off neutron-server on control node
  service: name=neutron-server state=stopped

- name: turn off keepalived on control node
  service: name=keepalived state=stopped
  when: ansible_os_family == "Debian"

- name: stop neutron l3 agent
  service: name=neutron-l3-agent state=stopped enabled=no
  when: odl_l3_agent == "Enable" and inventory_hostname in groups['odl']

- name: remove neutron l3 agent
  shell: >
    sed -i '/neutron-l3-agent/d' /opt/service;
    rm -rf /lib/systemd/system/neutron-l3-agent.service;
    rm -rf /etc/init/neutron-l3-agent.conf;
    rm -rf /etc/init.d/neutron-l3-agent;
  when: odl_l3_agent == "Enable" and inventory_hostname in groups['odl']

