##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

- name: get image http server
  shell: awk -F'=' '/compass_server/ {print $2}' /etc/compass.conf
  register: http_server

- name: download oracle-jdk8 package file
  get_url:
    url: "http://{{ http_server.stdout_lines[0] }}/packages/onos/{{ jdk8_pkg_name }}"
    dest: /opt/{{ jdk8_pkg_name }}

- name: download oracle-jdk8 script file
  get_url:
    url: "http://{{ http_server.stdout_lines[0] }}/packages/onos/{{ jdk8_script_name }}"
    dest: /opt/

- name: download odl package
  get_url:
    url: "http://{{ http_server.stdout_lines[0] }}/packages/odl/{{ odl_pkg_url }}"
    dest: /opt/{{ odl_pkg_name }}

- name: download odl pip package
  get_url:
    url: "http://{{ http_server.stdout_lines[0] }}/pip/{{ networking_odl_pkg_name }}"
    dest: /opt/{{ networking_odl_pkg_name }}
