##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

- name: chown opendaylight directory and files
  shell: >
    chown -R odl:odl "{{ odl_home }}";
    chown odl:odl "{{ service_file.dst }}";

- name: start opendaylight
  service: name=opendaylight state=started
  when: ansible_os_family == "Debian"

- name: set opendaylight autostart
  shell: chkconfig opendaylight on
  when: ansible_os_family == "RedHat"

- name: start opendaylight
  shell: service opendaylight start
  when: ansible_os_family == "RedHat"

- name: check if opendaylight running
  shell: |
    netstat -lpen --tcp | grep java |  grep 6653;
    while [ $? -ne 0 ]; do sleep 10; netstat -lpen --tcp | grep java \
        | grep 6653; done
