##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---

- name: download packages
  include: 01_00_download_packages.yml

- name: create odl user and group
  include: 01_01_create_odl_user_and_group.yml

- name: unarchive odl and jdk
  include: 01_02_unarchive_odl_and_jdk.yml

- name: copy odl configuration files
  include: 01_03_copy_odl_configuration_files.yml

- name: install pip packages
  include: 01_04_install_pip_packages.yml

- name: clean up karaf data
  include: 01_05_clean_up_karaf_data.yml

- name: stop openstack services
  include: 01_06_stop_openstack_services.yml

- name: set opendaylight cluster
  include: 05_set_opendaylight_cluster.yml
  when: groups['odl']|length > 1

- name: install moon
  include: moon-odl.yml
  when: moon == "Enable"

- name: start and check odl
  include: 01_07_start_check_odl.yml

- name: run openswitch
  include: 03_openvswitch.yml

- name: configure neutron
  include: 01_08_configure_neutron.yml
