---
TYPE: baremetal
FLAVOR: cluster
POWER_TOOL: ipmitool

ipmiUser: root
ipmiVer: '2.0'

hosts:
  - name: host1
    mac: 'E0:97:96:10:67:83'
    interfaces:
      - eth1: 'E0:97:96:10:67:8B'
    ipmiIp: 192.168.5.173
    ipmiPass: Huawei12#$
    roles:
      - controller
      - ha
      - onos
      - ceph-adm
      - ceph-mon

  - name: host2
    mac: 'E0:97:96:10:5A:C8'
    interfaces:
      - eth1: 'E0:97:96:10:5A:D0'
    ipmiIp: 192.168.5.174
    ipmiPass: Huawei12#$
    roles:
      - controller
      - ha
      - onos
      - ceph-mon

  - name: host3
    mac: 'E0:97:96:10:67:4D'
    interfaces:
      - eth1: 'E0:97:96:10:67:55'
    ipmiIp: 192.168.5.175
    ipmiPass: Huawei12#$
    roles:
      - controller
      - ha
      - onos
      - ceph-mon

  - name: host4
    mac: 'E0:97:96:10:5D:44'
    interfaces:
      - eth1: 'E0:97:96:10:5D:4C'
    ipmiIp: 192.168.5.176
    ipmiPass: Huawei12#$
    roles:
      - compute
      - ceph-osd

  - name: host5
    mac: 'E0:97:96:10:63:29'
    interfaces:
      - eth1: 'E0:97:96:10:63:31'
    ipmiIp: 192.168.5.177
    ipmiPass: Huawei12#$
    roles:
      - compute
      - ceph-osd
