# #############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
# #############################################################################
---
- name: Fetch openrc
  hosts: utility_all[0]
  max_fail_percentage: 20
  user: root
  tasks:
    - fetch:
        src: /root/openrc
        dest: /opt/openrc
        flat: "yes"
