# #############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
# #############################################################################
---
- name: Installation and setup of Neutron
  hosts: neutron_openvswitch_agent
  gather_facts: "{{ gather_facts | default(True) }}"
  max_fail_percentage: 20
  user: root
  tasks:
    - name: stop neutron-openvswitch-agent
      service:
        name: neutron-openvswitch-agent
        state: stopped

    # yamllint disable rule:line-length
    - name: change the openvswitch_agent.ini
      lineinfile:
        dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
        insertafter: '^bridge_mappings'
        line: "local_ip = {{ hostvars[inventory_hostname]['container_networks']['tunnel_address']['address'] }}"
      when:
        - inventory_hostname not in groups['nova_compute']

    - name: change the openvswitch_agent.ini
      lineinfile:
        dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
        regexp: '^bridge_mappings'
        insertafter: '^bridge_mappings'
        line: "local_ip = {{hostvars[inventory_hostname]['ansible_br_vxlan']['ipv4']['address']}}"
      notify:
        - Restart neutron-openvswitch-agent
      when:
        - inventory_hostname in groups['nova_compute']
    # yamllint enable rule:line-length

    - name: Setup br-provider
      openvswitch_bridge:
        bridge: br-provider
        state: present
      notify:
        - Restart neutron-openvswitch-agent
      when:
        - inventory_hostname not in groups['nova_compute']

    - name: Add port to br-provider
      openvswitch_port:
        bridge: br-provider
        port: "eth12"
        state: present
      notify:
        - Restart neutron-openvswitch-agent
      when:
        - inventory_hostname not in groups['nova_compute']

  handlers:
    - name: Restart neutron-openvswitch-agent
      service:
        name: neutron-openvswitch-agent
        state: restarted
