##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - test_odl

- name: Provision Common on all nodes
  include: 00_odl_common.yml
  when: groups['odl']|length !=0

- name: Provision ODL on Controller nodes
  include: 01_odl_controller.yml
  when: inventory_hostname in groups['odl']

#- name: Provision ODL on Compute nodes
#  include: 02_odl_compute.yml
#  when: groups['odl']|length !=0 and inventory_hostname not in groups['odl']
