---
node_network:
  nic_mappings:
    - name: eth0
      # pci bus/device/function
      bdf: 02:00.1

    - name: eth1
      bdf: 02:00.2

    - name: eth2
      bdf: 81:00.0

    - name: eth3
      bdf: 81:00.1

  bond_mappings:
    - name: bond0
      interface:
        - eth2
        - eth3
      mode: lacp

  bridge_mappings:
    - name: br-prv
      network: physnet
      interface: bond0
      type: ovs
      vlan_range:
        - 1
        - 4000

  interface_mappings:
    # install is just a alias to eth0, for compass install/admin
    - name: install
      interface: eth0
      vlan_tag: 4001
      type: vlan
      subnet: install

    # mgmt is a vlan interface on eth1, for inter-components
    - name: mgmt
      interface: eth1
      vlan_tag: 4001
      type: vlan
      subnet: mgmt

    # storage is a vlan interface on eth1, for storage data plane
    - name: storage
      interface: eth1
      vlan_tag: 4002
      type: vlan
      subnet: storage

    # public is just a alias for eth1, for external access to openstack api
    - name: public
      interface: eth1
      type: flat
      subnet: public

  subnets:
    - name: install
      ip_ranges:
        - - "10.1.0.1"
          - "10.1.0.254"
      cidr: "10.1.0.0/24"

    - name: mgmt
      ip_ranges:
        - - "172.16.1.1"
          - "172.16.1.254"
      cidr: "172.16.1.0/24"
      vip: 172.16.1.222

    - name: storage
      ip_ranges:
        - - "172.16.2.1"
          - "172.16.2.254"
      cidr: "172.16.2.0/24"

    - name: public
      ip_ranges:
        - - "192.168.50.210"
          - "192.168.50.220"
      cidr: "192.168.50.0/24"
      gw: "192.168.50.1"
      vip: 192.168.50.240
