##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
odl_username: admin
odl_password: admin
odl_api_port: 8181

netvirt_table: netvirt-providers-config:netvirt-providers-config
sfc_table: sfc-of-renderer:sfc-of-renderer-config

conf_netvirt:
  - url: http://{{ internal_vip.ip }}:{{ odl_api_port }}/restconf/config/{{ netvirt_table }}
    body: {"netvirt-providers-config":{"table-offset":1}}

# yamllint disable rule:line-length
conf_sfc:
  - url: http://{{ internal_vip.ip }}:{{ odl_api_port }}/restconf/config/{{ sfc_table }}
    body: {"sfc-of-renderer-config":{"sfc-of-table-offset":"150", "sfc-of-app-egress-table-offset":"11"}}
# yamllint enable rule:line-length

odl_pkg_url: distribution-karaf-0.5.2-Boron-SR2.tar.gz
odl_pkg_name: distribution-karaf-0.5.2-Boron-SR2.tar.gz
odl_home: "/opt/opendaylight/"
odl_base_features:
  - config
  - standard
  - region
  - package
  - kar
  - ssh
  - management
  - odl-restconf
  - odl-l2switch-switch
  - odl-openflowplugin-all
  - odl-mdsal-apidocs
  - odl-dlux-all
  - odl-adsal-northbound
  - odl-nsf-all
  - odl-ovsdb-openstack
  - odl-ovsdb-northbound
  - odl-dlux-core

odl_extra_features:
  - odl-restconf-all
  - odl-mdsal-clustering
  - odl-openflowplugin-flow-services
  - http
  - jolokia-osgi

odl_features: "{{ odl_base_features + odl_extra_features }}"


jdk8_pkg_name: jdk-8u51-linux-x64.tar.gz
jdk8_script_name: install_jdk8.tar

common_packages_noarch: []

odl_pip: networking-odl-3.2.0

networking_odl_pkg_name: networking-odl-3.2.0.tar.gz
