#############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- include: "{{ ansible_distribution }}.yml"
  when:
    - inventory_hostname in groups['compute']
    - ansible_distribution == 'Ubuntu'

# install networking-sfc for non odl scenarios
- include: install_networking_sfc.yml
  when:
    - opendaylight is not defined or opendaylight == "Disable"
    - inventory_hostname not in groups['horizon_all']

- include: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
    - inventory_hostname in groups['compute']

- include: ceilometer-upgrade.yml
  when:
    - inventory_hostname in groups['ceilometer_all']

- include: tacker_horizon.yml
  when: inventory_hostname in groups['horizon_all']

- include: novaclient_workaround.yml
  when: inventory_hostname in groups['utility']
