##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---
TYPE: virtual
FLAVOR: cluster

hosts:
  - name: host1
    roles:
      - kube_master
      - etcd
      - ha

  - name: host2
    roles:
      - kube_master
      - etcd
      - ha 

  - name: host3
    roles:
      - kube_master
      - etcd
      - ha

  - name: host4
    roles:
      - kube_node

  - name: host5
    roles:
      - kube_node
