TYPE: virtual
FLAVOR: cluster

hosts:
  - name: host1
    roles:
      - controller
      - ha
      - odl
      - ceph-adm
      - ceph-mon

  - name: host2
    roles:
      - controller
      - ha
      - odl
      - ceph-mon

  - name: host3
    roles:
      - controller
      - ha
      - odl
      - ceph-mon

  - name: host4
    roles:
      - compute

  - name: host5
    roles:
      - compute
