nic_mappings: []
bond_mappings: []

provider_net_mappings:
  - name: br-prv
    network: physnet
    interface: eth1
    type: ovs
    role:
      - controller
      - compute

sys_intf_mappings:
  - name: mgmt
    interface: eth1
    vlan_tag: 2
    role:
      - controller
      - compute

  - name: storage
    interface: eth1
    vlan_tag: 3
    role:
      - controller
      - compute

  - name: external
    interface: br-prv
    vlan_tag: 4
    role:
      - controller
      - compute

ip_settings:
  - name: mgmt
    ip_ranges:
    - - "172.16.1.1"
      - "172.16.1.254"
    cidr: "172.16.1.0/24"
    role:
      - controller
      - compute

  - name: storage
    ip_ranges:
    - - "172.16.2.1"
      - "172.16.2.254"
    cidr: "172.16.2.0/24"
    role:
      - controller
      - compute

  - name: external
    ip_ranges:
    - - "172.16.3.2"
      - "172.16.3.100"
    cidr: "172.16.3.0/24"
    gw: "172.16.3.1"
    role:
      - controller
      - compute

public_net_info:
  enable: False
  network: ext-net
  type: vlan
  segment_id: 1000
  subnet: ext-subnet
  provider_network: physnet
  router: router-ext
  enable_dhcp: False
  no_gateway: False
  external_gw: "172.16.3.1"
  floating_ip_cidr: "172.16.3.0/24"
  floating_ip_start: "172.16.3.100"
  floating_ip_end: "172.16.3.254"
