##############################################################################
# Copyright (c) 2016 baiguoku@huawei.com and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
openvswitch:
  tenant_network_type: vxlan
  network_vlan_ranges:
    - 'physnet:1:4094'
  bridge_mappings:
    - 'physnet:br-prv'
