##############################################################################
# Copyright (c) 2017 Orange and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
TYPE: baremetal
FLAVOR: cluster
POWER_TOOL: ipmitool

ipmiUser: orange
ipmiVer: '2.0'

hosts:
  - name: charlotteR630
    mac: '14:18:77:34:89:E2'
    interfaces:
      - eth1: 'A0:36:9F:4E:87:1A'
    ipmiIp: 172.31.2.116
    ipmiPass: orange2014*
    roles:
      - controller
      - ha
      - ceph-adm
      - ceph-mon

  - name: cookieR630
    mac: '14:18:77:34:A2:AC'
    interfaces:
      - eth1: 'A0:36:9F:4E:8B:AE'
    ipmiIp: 172.31.2.117
    ipmiPass: orange2014*
    roles:
      - controller
      - ha
      - ceph-osd
      - ceph-mon

  - name: cheesecakeR630
    mac: '14:18:77:34:8E:40'
    interfaces:
      - eth1: 'A0:36:9F:4E:8E:DA'
    ipmiIp: 172.31.2.119
    ipmiPass: orange2014*
    roles:
      - controller
      - ha
      - ceph-osd

  - name: eclairR730
    mac: 'EC:F4:BB:CB:62:AC'
    interfaces:
      - eth1: 'EC:F4:BB:CB:62:AA'
    ipmiIp: 172.31.2.123
    ipmiPass: orange2014*
    roles:
      - compute
      - ceph-osd

  - name: chouR730
    mac: 'EC:F4:BB:CB:5F:64'
    interfaces:
      - eth1: 'EC:F4:BB:CB:5F:62'
    ipmiIp: 172.31.2.120
    ipmiPass: orange2014*
    roles:
      - compute
      - ceph-osd
