##############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: remove resolv.conf
  file: "dest=/etc/resolv.conf state=absent"

- name: make a symbolic link
  shell: "ln -s /var/run/resolvconf/resolv.conf /etc/resolv.conf"

- name: configure controller network
  template:
    src: controller.j2
    dest: /etc/network/interfaces
  notify:
    - restart network service
