##############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: configure controller network
  template:
    src: controller.j2
    dest: /etc/network/interfaces
  notify:
    - restart network service

- name: check apt source
  shell: "ping -c 2 192.168.137.222 > /dev/null"
  register: checkresult
  ignore_errors: "true"

- name: change sources list(apt)
  template:
    src: sources.list.lab
    dest: /etc/apt/sources.list
  when: checkresult.rc == 0

- name: change sources list(apt)
  template:
    src: sources.list.official
    dest: /etc/apt/sources.list
  when: checkresult.rc != 0
