nic_mappings: []
bond_mappings: []

provider_net_mappings:
  - name: br-prv
    network: physnet
    interface: eth3
    type: ovs
    role:
      - controller
      - compute

sys_intf_mappings:
  - name: mgmt
    interface: eth2
    vlan_tag: 804
    type: vlan
    role:
      - controller
      - compute

  - name: storage
    interface: eth2
    vlan_tag: 802
    type: vlan
    role:
      - controller
      - compute

  - name: external
    interface: br-prv
    vlan_tag: 805
    type: vlan
    role:
      - controller
      - compute

ip_settings:
  - name: mgmt
    ip_ranges:
    - - "10.8.14.1"
      - "10.8.14.254"
    cidr: "10.8.14.0/24"
    role:
      - controller
      - compute

  - name: storage
    ip_ranges:
    - - "10.8.12.1"
      - "10.8.12.254"
    cidr: "10.8.12.0/24"
    role:
      - controller
      - compute

  - name: external
    ip_ranges:
    - - "10.8.15.1"
      - "10.8.15.254"
    cidr: "10.8.15.0/24"
    role:
      - controller
      - compute

internal_vip:
  ip: 10.8.14.222
  netmask: "24"
  interface: mgmt

public_vip:
  ip: 10.8.15.222
  netmask: "24"
  interface: external

onos_nic: eth4
public_net_info:
  enable: True
  network: ext-net
  type: flat
  segment_id: 10
  subnet: ext-subnet
  provider_network: physnet
  router: router-ext
  enable_dhcp: False
  no_gateway: False
  external_gw: "10.8.15.1"
  floating_ip_cidr: "10.8.15.0/24"
  floating_ip_start: "10.8.15.100"
  floating_ip_end: "10.8.15.200"
