##############################################################################
# Copyright (c) 2017 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: replace http with https in openrc
  replace:
    dest: /opt/openrc
    regexp: "http://"
    replace: "https://"

- name: replace internalURL with publicURL in openrc
  replace:
    dest: /opt/openrc
    regexp: "{{ internal_vip['ip'] }}"
    replace: "{{ public_vip['ip'] }}"

- name: change the endpoint type
  replace:
    dest: /opt/openrc
    regexp: "internalURL"
    replace: "publicURL"

- name: add the IP of SDN controller
  lineinfile:
    dest: /opt/openrc
    state: present
    line: "SDN_CONTROLLER_IP: {{ public_vip['ip'] }}"
